<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     * 
     * This migration creates the transactions table to store all payment transaction records
     * from SSL Commerz payment gateway. Each transaction represents a payment attempt
     * whether successful, failed, or cancelled.
     */
    public function up(): void
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->id();
            
            // Transaction identifiers
            $table->string('transaction_id')->unique()->comment('Unique transaction ID generated by our system');
            $table->string('order_id')->nullable()->comment('SSL Commerz order ID (tran_id)');
            
            // Customer information
            $table->string('customer_name')->comment('Customer full name');
            $table->string('customer_email')->comment('Customer email address');
            $table->string('customer_phone', 20)->nullable()->comment('Customer phone number');
            $table->text('customer_address')->nullable()->comment('Customer shipping/billing address');
            $table->string('customer_city')->nullable()->comment('Customer city');
            $table->string('customer_postcode', 20)->nullable()->comment('Customer postal/zip code');
            $table->string('customer_country')->nullable()->default('Bangladesh')->comment('Customer country');
            
            // Product/Order details
            $table->string('product_name')->comment('Product or service name');
            $table->text('product_description')->nullable()->comment('Detailed product description');
            $table->string('product_category')->nullable()->comment('Product category');
            
            // Payment amount details
            $table->decimal('amount', 10, 2)->comment('Transaction amount in BDT');
            $table->decimal('paid_amount', 10, 2)->nullable()->comment('Actual amount paid (may differ due to charges)');
            $table->string('currency', 3)->default('BDT')->comment('Currency code (BDT, USD, etc.)');
            
            // SSL Commerz gateway response data
            $table->string('gateway_transaction_id')->nullable()->comment('Transaction ID from SSL Commerz');
            $table->string('bank_transaction_id')->nullable()->comment('Bank transaction reference ID');
            $table->string('card_type')->nullable()->comment('Payment card type (Visa, Master, etc.)');
            $table->string('card_no')->nullable()->comment('Masked card number');
            $table->string('card_issuer')->nullable()->comment('Card issuing bank name');
            $table->string('card_brand')->nullable()->comment('Card brand name');
            $table->string('card_issuer_country')->nullable()->comment('Card issuer country');
            $table->string('payment_method')->nullable()->comment('Payment method used (card, mobile banking, etc.)');
            
            // Transaction status and tracking
            $table->enum('status', ['pending', 'processing', 'success', 'failed', 'cancelled', 'refunded'])
                  ->default('pending')
                  ->comment('Current transaction status');
            $table->string('validation_status')->nullable()->comment('SSL Commerz validation status (VALID, VALIDATED, etc.)');
            $table->string('risk_level')->nullable()->comment('Risk level assessment (0, 1, 2)');
            $table->string('risk_title')->nullable()->comment('Risk assessment description');
            
            // SSL Commerz session and reference data
            $table->string('sessionkey')->nullable()->comment('SSL Commerz session key');
            $table->string('gateway_page_url')->nullable()->comment('SSL Commerz payment gateway URL');
            
            // Transaction metadata
            $table->string('value_a')->nullable()->comment('Custom value A for additional data');
            $table->string('value_b')->nullable()->comment('Custom value B for additional data');
            $table->string('value_c')->nullable()->comment('Custom value C for additional data');
            $table->string('value_d')->nullable()->comment('Custom value D for additional data');
            
            // API response storage
            $table->text('api_response')->nullable()->comment('Full API response from SSL Commerz (JSON)');
            $table->text('ipn_response')->nullable()->comment('IPN (Instant Payment Notification) response data');
            
            // Timestamps and soft deletes
            $table->timestamp('paid_at')->nullable()->comment('Timestamp when payment was completed');
            $table->timestamps();
            $table->softDeletes()->comment('Soft delete timestamp for record retention');
            
            // Indexes for faster queries
            $table->index('transaction_id');
            $table->index('order_id');
            $table->index('gateway_transaction_id');
            $table->index('status');
            $table->index('customer_email');
            $table->index(['status', 'created_at']); // Composite index for status-based date queries
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('transactions');
    }
};
